apiVersion: v1
kind: Pod 
metadata:
   name: redis 
   labels:
     app: redis
spec:
  containers:
    - image: redis:alpine
      name: redis
      ports:
        - containerPort: 6379
          name: redis

