apiVersion: v1
kind: Pod 
metadata:
   name: result
   labels:
     app: result
spec:
  containers:
    - image: dockersamples/examplevotingapp_result
      name: result
      ports:
        - containerPort: 80
          name: result

