apiVersion: apps/v1
kind: Deployment
metadata:
   name: db
   labels:
     app: db
spec:
  replicas: 2
  selector:
    matchLabel:
       app: db
  template:
    metadata:
      name: db 
      labels:
        app: db
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          ports:
            - containerPort: 5432
              name: postgres