apiVersion: apps/v1
kind: Deployment
metadata:
   name: worker
   labels:
     app: worker
spec:
  replicas: 2
  selector:
    matchLabel:
       app: worker
  template:
    metadata:
      name: worker 
      labels:
        app: worker
    spec:
      containers:
        - image: dockersamples/examplevotingapp_worker
          name: worker